easy_admin:
  entities:
    User:
        class: App\Entity\User
        form:
            fields:
            - { property: 'prenom', label: "Prénom"}
            - { property: 'nom', label: "Nom"}
            - { property: 'email'}
            - { property: 'roles', type: "collection" }
        list:
          actions:
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
          fields:
            - { property: 'prenom', label: "Prénom"}
            - { property: 'nom', label: "Nom"}
            - { property: 'email'}
            - { property: 'roles'}